In [1]:
import numpy as np

In [7]:
X = np.arange(9).reshape(3, 3)
print(X)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


vertically downwards across rows (axis 0):

In [17]:
print(X.mean(axis=0, dtype=np.int64))

[3 4 5]


horizontally across columns (axis 1):

In [18]:
print(X.mean(axis=1, dtype=np.int64))

[1 4 7]


In [20]:
print(X.mean())

4.0


In [21]:
print(X.std(axis=0))

[2.44948974 2.44948974 2.44948974]


In [22]:
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

The line below gets the line number 1 and 2 (specified by the list before the comma) and all the columns (specified by :)

In [44]:
X[[1, 2],:]

array([[3, 4, 5],
       [6, 7, 8]])